In [6]:
# Data Loading

import pandas as pd
from pathlib import Path

# Find CSV files in the project folder
csv_files = Path("..").rglob("*.csv")

# Store datasets
data = {}

# Load each CSV file
for file in csv_files:
    dataset_name = file.stem
    data[dataset_name] = pd.read_csv(file)

# Display loaded datasets
for name, df in data.items():
     print(f"{name}: {df.shape}")

customers: (1006, 4)
kitchens: (25, 5)
menu_items: (45270, 6)
orders: (20120, 10)

In [7]:
# Data Inspect

for name, df in data.items():
    print(f"\n{'='*50}")
    print(name.upper())
    print(f"\n{'='*50}")

    print("Rows:", df.shape[0])
    print("Column:",df.shape[1])

==================================================
CUSTOMERS

==================================================
Rows: 1006
Column: 4

==================================================
KITCHENS

==================================================
Rows: 25
Column: 5

==================================================
MENU_ITEMS

==================================================
Rows: 45270
Column: 6

==================================================
ORDERS

==================================================
Rows: 20120
Column: 10

In [8]:
# Preview the data

for name, df in data.items():
    print(f"\n{'='*50}")
    print(name.upper())
    print(f"\n{'='*50}")

    display(df.head())

==================================================
CUSTOMERS

==================================================

  customer_id       city signup_date customer_segment
0   CUS-00001  Bengaluru  2024-08-07              New
1   CUS-00002  Ahmedabad  2024-06-11              NaN
2   CUS-00003    Kolkata  2024-08-07          Premium
3   CUS-00004  Hyderabad  2024-09-26          Regular
4   CUS-00005     Mumbai  2025-09-23          Regular

==================================================
KITCHENS

==================================================

  kitchen_id          kitchen_name            zone  monthly_rent  staff_count
0    KIT-001   Tasty Trail Central    Central Zone         73989           16
1    KIT-002     Dish Dock Central    Central Zone         76733           19
2    KIT-003  Cravings Corner Tech  Tech Park Belt        113123           11
3    KIT-004       Grill Grove Old        Old City        210936            7
4    KIT-005     Bite Bazaar South      South Zone         91696           12

==================================================
MENU_ITEMS

==================================================

,item_id,order_id,item_name,category,quantity,unit_price
0,ITM-000001,ORD-016728,Schezwan Noodles,Noodles,4,242.07
1,ITM-000002,ORD-016728,Mutton Biryani,Biryani,2,285.05
2,ITM-000003,ORD-016728,Chicken Zinger Burger,Burger,1,232.88
3,ITM-000004,ORD-010614,Singapore Noodles,Noodles,1,275.71
4,ITM-000005,ORD-010614,Egg Biryani,Biryani,3,295.28

==================================================
ORDERS

==================================================

,order_id,customer_id,kitchen_id,order_date,order_value,discount,delivery_fee,delivery_distance_km,delivery_time_min,order_status
0,ORD-000001,CUS-00432,KIT-006,2025-03-27 13:56:00,419.48,13.93,34.73,2.55,19.4,Delivered
1,ORD-000002,CUS-00840,KIT-013,2025-06-14 21:35:00,710.98,12.65,38.14,3.39,24.1,Delivered
2,ORD-000003,CUS-00729,KIT-003,2025-10-03 15:06:00,356.76,4.16,23.35,0.50,10.0,Cancelled
3,ORD-000004,CUS-00592,KIT-019,2025-11-21 09:46:00,644.31,12.40,27.30,1.09,18.1,Delivered
4,ORD-000005,CUS-00725,KIT-002,2025-06-07 18:56:00,195.31,0.00,22.99,0.50,13.7,Cancelled

In [9]:
# Summarise datatypes

for name, df in data.items():
    print(f"\n{'='*50}")
    print(name.upper())
    print(f"\n{'='*50}")

    print(df.dtypes)

==================================================
CUSTOMERS

==================================================
customer_id         str
city                str
signup_date         str
customer_segment    str
dtype: object

==================================================
KITCHENS

==================================================
kitchen_id        str
kitchen_name      str
zone              str
monthly_rent    int64
staff_count     int64
dtype: object

==================================================
MENU_ITEMS

==================================================
item_id           str
order_id          str
item_name         str
category          str
quantity        int64
unit_price    float64
dtype: object

==================================================
ORDERS

==================================================
order_id                    str
customer_id                 str
kitchen_id                  str
order_date                  str
order_value             float64
discount                float64
delivery_fee            float64
delivery_distance_km    float64
delivery_time_min       float64
order_status                str
dtype: object

In [10]:
# Check Missing Values

for name, df in data.items():
    print(f"\n{'='*50}")
    print(name.upper())
    print(f"\n{'='*50}")

    print(df.isna().sum())

==================================================
CUSTOMERS

==================================================
customer_id          0
city                 0
signup_date          0
customer_segment    10
dtype: int64

==================================================
KITCHENS

==================================================
kitchen_id      0
kitchen_name    0
zone            0
monthly_rent    0
staff_count     0
dtype: int64

==================================================
MENU_ITEMS

==================================================
item_id         0
order_id        0
item_name       0
category        0
quantity        0
unit_price    452
dtype: int64

==================================================
ORDERS

==================================================
order_id                  0
customer_id               0
kitchen_id                0
order_date                0
order_value             160
discount                  0
delivery_fee            161
delivery_distance_km    616
delivery_time_min       712
order_status              0
dtype: int64

In [11]:
# Duplicacy checking for Primary Key

pk= {
    "customers":"customer_id",
    "kitchens":"kitchen_id",
    "menu_items":"item_id",
    "orders":"order_id"
}

for name, column in pk.items():
    duplicate_counts=data[name][column].duplicated().sum()

    print(f"{name}.{column}:{duplicate_counts} duplicate values")

customers.customer_id:6 duplicate values
kitchens.kitchen_id:0 duplicate values
menu_items.item_id:270 duplicate values
orders.order_id:120 duplicate values

In [12]:
# Check Unique Values for Categorical Columns

cat_cols={
    "customers":["city","customer_segment"],
    "kitchens":["zone"],
    "menu_items":["category"],
    "orders":["order_status"]
}

for name, columns in cat_cols.items():
    print(f"\n{'='*50}")
    print(name.upper())
    print(f"{'='*50}")

    for column in columns:
        print(f"\n{column}:")
        print(data[name][column].value_counts(dropna=False))

==================================================
CUSTOMERS
==================================================

city:
city
Mumbai           202
Bengaluru        151
Delhi            147
Hyderabad        115
Chennai          101
Kolkata           97
Pune              93
Ahmedabad         80
KOLKATA            2
chennai            2
  Delhi            2
CHENNAI            2
  Mumbai           2
hyderabad          2
HYDERABAD          2
  Ahmedabad        1
  Bengaluru        1
  Pune             1
PUNE               1
  Chennai          1
delhi              1
Name: count, dtype: int64

customer_segment:
customer_segment
Regular    548
New        298
Premium    150
NaN         10
Name: count, dtype: int64

==================================================
KITCHENS
==================================================

zone:
zone
Central Zone      6
North Zone        5
Old City          4
Suburban Ring     3
East Zone         3
South Zone        2
Tech Park Belt    1
West Zone         1
Name: count, dtype: int64

==================================================
MENU_ITEMS
==================================================

category:
category
Pasta       4587
Biryani     4573
Noodles     4529
Pizza       4483
Dessert     4483
Burger      4469
Wrap        4458
Sandwich    4448
Rice        4413
Beverage    4375
Misc          77
beverage      28
pizza         28
burger        26
sandwich      25
WRAP          24
dessert       23
biryani       23
noodles       22
pasta         20
PASTA         19
wrap          18
SANDWICH      17
BIRYANI       16
rice          16
BURGER        16
DESSERT       16
PIZZA         12
RICE          10
BEVERAGE       8
NOODLES        8
Name: count, dtype: int64

==================================================
ORDERS
==================================================

order_status:
order_status
Delivered    17091
Cancelled     2036
Refunded       793
delivered       60
DELIVERED       58
Deliverd        51
Canceled        12
refunded         8
cancelled        6
REFUNDED         3
CANCELLED        2
Name: count, dtype: int64

In [13]:
# Numeric Data Inspections

for name, df in data.items():
    print(f"\n{'='*50}")
    print(name.upper())
    print(f"\n{'='*50}")

    display(df.describe().T)

==================================================
CUSTOMERS

==================================================

                 count unique         top freq
customer_id       1006   1000   CUS-00412    2
city              1006     21      Mumbai  202
signup_date       1006    549  2025-06-16    8
customer_segment   996      3     Regular  548

==================================================
KITCHENS

==================================================

,count,mean,std,min,25%,50%,75%,max
monthly_rent,25.0,120662.52,53004.615415,66487.0,73989.0,105396.0,135636.0,235348.0
staff_count,25.0,11.28,5.511503,4.0,7.0,11.0,13.0,23.0

==================================================
MENU_ITEMS

==================================================

,count,mean,std,min,25%,50%,75%,max
quantity,45270.0,1.971681,1.132399,0.00,1.00,2.00,3.0000,5.00
unit_price,44818.0,203.001746,97.211544,-419.83,134.42,188.01,250.1075,549.76

==================================================
ORDERS

==================================================

,count,mean,std,min,25%,50%,75%,max
order_value,19960.0,575.760832,356.920907,-294.93,342.29,493.965,717.8275,5977.13
discount,20120.0,18.510025,52.146514,0.00,0.00,0.000,14.7125,874.16
delivery_fee,19959.0,51.445389,30.235607,-48.14,28.70,41.710,64.2600,169.89
delivery_distance_km,19504.0,5.257035,4.966389,0.00,1.46,3.650,7.4325,34.07
delivery_time_min,19408.0,29.424036,17.771148,0.00,15.70,25.400,38.2000,155.50